CSS File
rogeliomonterde/hello pull request #1
Opened 2023-01-10 19:01 UTC by rogeliomonterde

hi

2023-01-10 19:23 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @rogeliomonterde, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 

## Required Changes ♻️
_Check the comments under the review._

You did a good job following the requirements 🚀. However, there are still some things that you need to improve in order to move on:

- [ ] I see that you tried to set up the linters, however, they are not working at the moment due to a typo in the `.github/workflows` folder. You missed the `"s"`. Please consider following [this spet-by-step tutorial](https://github.com/microverseinc/linters-config/tree/master/html-css) paying extra attention to naming the files and folders correctly in order to have linters up and running! 🤓 🛠️ 

- [ ] Please consider using the [Microverse's Readme Template](https://github.com/microverseinc/readme-template). During the whole program you're going to be asked to write documentation for your projects, so please have a look at it, get familiar with it, and consider adding it to your project (copying its contents but using your project information). 🤓 🛠️ 

- [ ] Also, please consider adding a better description for your pull request describing in detail the changes you are implementing. 🤓 🛠️ 

![image](https://user-images.githubusercontent.com/77069011/211642516-eb9098a0-c62e-47d3-88e4-481db6edc4d8.png)

At the moment `"hi"` is not a good description, please consider editing it! 🚀 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-10 21:45 UTC, rogeliomonterde commented
Hi I could solve the problems on my local repository but I have problems updating the file here

2023-01-10 21:46 UTC, rogeliomonterde commented
I dont know if I did it correctly
when i try to push the main branch comes this errror:

o github.com:rogeliomonterde/hello.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'github.com:rogeliomonterde/hello.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

2023-01-11 00:01 UTC, DuaneDave requested changes
Hi @rogeliomonterde 👋 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ Linters are set up
✔️ All files are present


 ## Required Changes ♻️
- To keep our codebase free of mistakes, it is advisable that all linters checks be green. kindly resolve the stylint error to follow this pattern of mistake-free code.

see below

![61BE4693-88F5-4980-A71E-CBCFB0B9E0EA](https://user-images.githubusercontent.com/84930355/211688199-222f7d22-996a-43a2-a273-0cf89aecd229.jpeg)



- As previously requested, do consider adding a better description for your pull request describing in detail the changes you are implementing in order to make it clear the activities done for this project.
Instead of hi, enumerate the things done in this milestone eg
    - set up linters
    - Add HTML file with tags
    - Add CSS file with styling
    - Add test.md file
    - Ignored some files in gitignore

Click on the three dots by the right corner to edit

![55BAB2D1-92BA-4999-9B5D-479463D2F712](https://user-images.githubusercontent.com/84930355/211688969-5f319b61-133e-4aa0-a0ff-9cc927f6f396.jpeg)


_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-11 00:01 UTC, DuaneDave commented on README.md
> +
Good job implementing the prescribed readme template but currently you have it duplicated. Please consider removing from line 271 downwards to make the documentation not repetitive and cumbersome.

2023-01-11 00:01 UTC, DuaneDave commented on README.md
> +</details>
Consider updating the tech stack provided in the template to the ones you have actually used (`html` and `CSS`) in order to have a readme that is consistent with the project

2023-01-11 00:01 UTC, DuaneDave commented on README.md
> +
Please add at least three cool features about this project here as they will easily draw the attention of any user to what they should expect from this project.

2023-01-11 00:01 UTC, DuaneDave commented on README.md
> +
This section should include a step-by-step guide as to what a user should do in order to get this project working  on their local machine. Kindly add such so new users of this project will know how to get it all set up 😄

2023-01-11 00:01 UTC, DuaneDave commented on README.md
> +```
Also, I recommend that you hint to users on how tests could be run on this project. Kindly add the commands needed to check for linter errors here in order to help new users get started.

2023-01-11 00:01 UTC, DuaneDave commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
Sometimes, users would love to follow or contact you on your social handles, in view of this, I suggest including your social handles here.

2023-01-11 00:01 UTC, DuaneDave commented on README.md
> +
Please add at least three future features for this project here in order to keep users noticed of future changes to come.

2023-01-11 00:01 UTC, DuaneDave commented on README.md
> +
Please include an acknowledgement giving credit to those whose ideas or code were used in this project to avoid plagiarizing

2023-01-11 00:33 UTC, DuaneDave commented
> I dont know if I did it correctly when i try to push the main branch comes this errror:
> 
> o github.com:rogeliomonterde/hello.git ! [rejected] main -> main (fetch first) error: failed to push some refs to 'github.com:rogeliomonterde/hello.git' hint: Updates were rejected because the remote contains work that you do hint: not have locally. This is usually caused by another repository pushing hint: to the same ref. You may want to first integrate the remote changes hint: (e.g., 'git pull ...') before pushing again. hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Whenever you encounter this issue again, please run git pull as the beach you are pushing have some changes that you do not have locally then run git push

2023-01-11 21:25 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️

Hi @rogeliomonterde , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-11 21:25 UTC, bobb-Rob commented on README.md
> +  </ul>
As mentioned by the previous reviewer, please consider updating the tech stack section according to your project. You will do this for all your microverse projects. 
![image](https://user-images.githubusercontent.com/84156714/211920422-082795a7-6406-4f93-a3bc-0fe93bf5e275.png)

2023-01-11 21:25 UTC, bobb-Rob commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/linkedinhandle)
Please edit this contact section as well and add your social media handles.

2023-01-11 21:25 UTC, bobb-Rob commented on index.html
> +    <meta charset="UTF-8">
- [ ] As mentioned by the previous reviewer, your Pull Request title and summary/description is still not written professionally, Kindly follow the instructions on [the previous review](https://github.com/rogeliomonterde/hello/pull/1#pullrequestreview-1243113454).
- [ ] There are conflicts in your code files. [Please read through this article to learn to resolve code conflicts](https://akshayranganath.github.io/Git-Pull-Handling-Merge-Conflict/).
- [ ] Kindly go through all the changes requested by other reviewers and make changes accordingly. Thank you

2023-01-12 19:03 UTC, closed without merging